[package]
name = "csproject"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.1", features = ["secrets"] }
rocket_dyn_templates = { version = "0.2.0", features = ["handlebars"] }
rocket_sync_db_pools = { version = "0.1.0", features = ["sqlite_pool"] }
serde = { version = "1.0.229", features = ["derive"] }
dashmap = { version = "6.2.1" }
smol = { version = "2.0.2" }
env_logger = { version = "0.11.11" }
log = { version = "0.4.34" }

[features]
default = ["secure"]
secure = ["rocket/tls"]

