[package]
name = "csproject"
version = "0.1.0"
edition = "2024"

[dependencies]
smol = { version = "2.0.2" }
env_logger = { version = "0.11.11" }
log = { version = "0.4.34" }
rand = { version = "0.10.2", features = ["sys_rng", "std_rng"] }
base64 = { version = "0.23.1" }
argon2 = { version = "0.6.0", features = ["getrandom"] }
derive_more = { version = "2.1.1", features = ["from", "display", "error"] }

[dependencies.rocket]
path = "./deps/Rocket/core/lib"
features = ["secrets"]

[dependencies.rocket_dyn_templates]
path = "./deps/Rocket/contrib/dyn_templates"
features = ["handlebars"]

[dependencies.rocket_sync_db_pools]
path = "./deps/Rocket/contrib/sync_db_pools/lib"
features = ["sqlite_pool"]

[features]
default = ["secure"]
secure = ["rocket/tls"]
# Enables unwrapping Result in most places in order to get more detailed
# information for debugging purposes.
check = []

